# Generated by Django 2.2 on 2019-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revheads_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_begin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
