# Generated by Django 2.2 on 2019-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revheads_app', '0002_auto_20190415_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
